{% set version = "1.2.3" %}

package:
  name: artview
  version: {{ version }}

source:
  fn: artview-{{ version }}.tar.gz
  url: https://github.com/nguy/artview/releases/download/Release_v1.2/artview-{{ version }}.tar.gz
  sha256: 9fd8c78439f9a3867a1a4579c5430f9b0338d1b7652e34ccb3e7a008a202b4b2

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - arm_pyart >=1.5
    - matplotlib >=1.1
    - pyqt >=4.6
  run:
    - python
    - arm_pyart >=1.5
    - matplotlib >=1.1
    - pyqt >=4.6

test:
  imports:
    - artview

about:
  home: https://github.com/nguy/artview
  license: BSD 3-Clause
  summary: ARM Radar Toolkit Viewer

extra:
  recipe-maintainers:
    - jjhelmus
