{% set version = "1.3.7" %}

package:
  name: artview
  version: {{ version }}

source:
  fn: artview-{{ version }}.tar.gz
  url: https://github.com/nguy/artview/archive/v{{ version }}.tar.gz
  sha256: 96b8572e3c5395bca43697723949383ff9b911021818b361c232968dcaa355da

build:
  noarch: python
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
    - arm_pyart >=1.6
    - matplotlib-base >=1.1, <3
    - pyqt >=4.6
  run:
    - python
    - arm_pyart >=1.6
    - matplotlib-base >=1.1, <3
    - pyqt >=4.6

test:
  imports:
    - artview
  commands:
    - artview -h

about:
  home: https://github.com/nguy/artview
  license: BSD 3-Clause
  license_file: LICENSE.md
  summary: ARM Radar Toolkit Viewer

extra:
  recipe-maintainers:
    - jjhelmus
    - nguy
    - dopplershift
