{% set version = "1.3.7" %}

package:
  name: artview
  version: {{ version }}

source:
  fn: artview-{{ version }}.tar.gz
  url: https://github.com/nguy/artview/archive/v{{ version }}.tar.gz
  sha256: 96b8572e3c5395bca43697723949383ff9b911021818b361c232968dcaa355da

build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    - arm_pyart >=1.5
    - matplotlib >=1.1
    - pyqt 4.11.*
  run:
    - python
    - arm_pyart >=1.5
    - matplotlib >=1.1
    - pyqt 4.11.*

test:
  imports:
    - artview

about:
  home: https://github.com/nguy/artview
  license: BSD 3-Clause
  summary: ARM Radar Toolkit Viewer

extra:
  recipe-maintainers:
    - jjhelmus
