travis:
  secure:
    BINSTAR_TOKEN: LdCYEs/BwrhcbIq81YSodZ9unUnKJ90dX+VOmhf9YJs4v3+1PeRaFA6bVedl6c3y6nQFTQAKcO+MVa7ZSDstTJIIdJuIEL+Tykp2ZAUiTN9vy7nMfAF1eJYyWrMewFOxJ5nRrSk8wPeMRBnQHs2HEerZ7UE8vZUsNQjinjabZw8h8JY6qIVpyXYoMiipSc3cSPi1yohspYaFYxTVlwhBf0p1d8e0ruonqWVCVOsTSewo1eoofeu1iHk5aZPUvxbqQ2cg7atKgDIBZraFSlQf4Pxo3bQJ14ueOqM3G35yxPpl1/Pn3hATvBwHKpwzAIuECNjAUdrnvA/E8Agf2gH92mtfV6cOQMUhMCl+BWc2LCMWyCZdXkbMH4KuhTKCemEwgDkOGq2M+CGoVP8HAl4O8lRt2L5zR7I89dc35YTXC/XSWSnU3L0vFPb5KRHQHmhsEx7tgAS+adIcga2NOCukSlpWUwg6lsqQUvLEnBWTFjeGERYkdWM3nvvgtcbXEQJ9B28QcGbP5drEJWXbkrP0Br4HwY5Ahj0dhv3XPV7nAKo5CT21k6v4T6405ZGJtOqytIdTPN3aKV88JBv2vvr48HMH1zwyA2ytRanK0y1tCF41VjFb3ij22iicT/ja0N1iNwngQAHeW26lhXrKcgaZdsIooceCh17H8X1EgOl33kY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
