travis:
  secure:
    BINSTAR_TOKEN: R11M03BGTlrcbbSIX//mJg3uAqBvXcWYG373EEZ5IdYInzpekCYyyOOeKhKMel1anEL5ypEpF/AiZsLb4vHNhTYWOcGZHyaYiGdCJJ3KED/VQzvYxv0alxIIl/TD3C9aRbFZk/baOy1EjlEDb87P81G47T5mUv/PeSAVymbDQYCc0PlUpClxH0MRRY6oRx/2NkDsO+LHInuI3P992ozCIiaC6TFdyiQjBML5Of3Py+oqBDqJtFssR/NOtLwJMbiMHjb7RygK1u8zP66jTTqXmUwMDZT2x9m3Yrkc1rJEOE/iN/7IgFQgyHQQD2hLfOwypS11pkObChoieaf5b6T3jXwq7O+3t6DFvBnC9gW4rR6+pkc2MoXiNHOj7xjt+ngY+LxoENmtJdpD7Ev4fWYGVVbznr+If7Jv4+Z6kGtwc6WQllCTjFJIpYE4/drT74IefRyLGR2r73P2VussF5CdRkLQf7DDXD5m+SL7QdG/YROcCKVC/qOXyFbCyzyVX1je8zvPoFs3rA2LN9HX07cHSFKNSW63wEmK4aYJ44Cisa5T4IMOJjU8lKGe274byG3GnGEtOOeXjDhvI6Lq6h+KRLCBlx6TZIZ8SM4qGFA5VrILBFUcnpbZSU7FZxXRLwHd8TwUCf9TWW/9aMCe/4x8JawdwX6Dmj2bICMDxamZqd4=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
