travis:
  secure:
    BINSTAR_TOKEN: TTzuoQLKeb4447Qzlmp8jyeSDSk67R2vcJetQUSeS67+zpJJdLchq2nRhmLp6edB8RNZxU+UZrYp4qHYmVwIFn8dclR+BmpqUfRMNcGApLy2MtXn7XnDZiwkA56PMpt6eKPbnO3HUh2PPJszqBMCqHUVTC+pXLb/t1W97DVooF3+CiK2SwpXiA8gb/AZ7Ge3EkE4zf2QQy9vbWNyAs8vDGF2JFP4AjRLStBWwrZNjgYk+WG4MI4zbKwOsz4PXu5L6tBtwrbfDILpWPxS81nyLrzYQ4k2rn/WCOPlP3jsCMNNIS39Z+jdSmu5aDJ6m5y7uzxjoIW0fd2yhXHQzlD4xBfphE/uxbQn0BihL8FResgV8lOz/1xpa/tU2MtAHYwcvllQfxqXt+hsaICPp+Hl/VjDS4NteKAnN4q9OFd8X7iu3nWTWdo032KIWK95O4eEn8+YguPaIGEkSgyp4s/ZkdVWNGaOWoD1Bv3zuZagzR4p5VlOQEJpEjTMl7GJ2bi0dvpYLaNWT5inor5dDXdhItYN1vDShnrFosyVLwO0yjiw857wKogzBMdfXoF2CacOTPjD7GQp8/9JrBpjkHfZW3/N9mrdQ8KzYSKVDIBOcVhUmuaudgZOeaDr8m24EITyewvTTrDXNsNzomnvhNaZMizxUniccYFaRfowgmad3p8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
