travis:
  secure:
    BINSTAR_TOKEN: PKTzqkXYCmyzkmTzYrDalclSdKIBgbUNuEwYCZo1/uwG5EibymiExVbEPiOHRElRlC2X/ot9P6gBI2IAybD1n33hspU4HMX/V7HVPtdZq9sZlCI+sSqwpcjfgWDR3EERpEGdUMLXxpW+sn5Fj2Mhw2rRESgj6tDYV+yGHvzV7M8nblNK/bXi7/nbBWd4DUdKnwaePaOIFf6q2mkzM8Mr2iPOlp3Moezle/hXbIYrpX9dIfrF52qnej9s8xQRXLJ7QQKRKsiUOFrAssqC0tNkBwOl+4+KkL2KXxqIQrSt8FMoMXndDakOwkUV+ICzDCoCPJpIXun8UDUGedIGmYwiklWlW23aP7cVcxLitkD0QcSOpDIa3eUEF/l2vObt1IfAcvmsK9CFOkoEzx7gEA3azZ60Z+JCD/mf5xA2WZKP0HCuABV2IuCFRaI+bo9cJToj0f0n5ZdLOp3jfxBVCMsfjOfPpSbXJl87NAhPpxYObZ6lULQL0+7EW59UdDWUUd6hmX7sq2yoy7gE/CxD3PrWCEb8qgy2GSsNssCoKJKB0XLXmBfNTmJ4tqyCNdAJGM82/IdSEK/SoK/KFV5ZQoQU2ReBzg8U61td63JETFQ28T4QQKRCkTy3M7Us4SCg7+Yv97zB/eTDhi6Zot4JkzSOi/TAitVo33bXGpnKsGiH6sw=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
